version: '2'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    container_name: parsley_health_test_sv_nodejs
    environment:
      NODE_ENV: develop
    volumes:
      - .:/app/parsley_health_test_sv
    ports:
      - "50:8000"
    restart: on-failure
    links:
      - mongodb
  mongodb:
    image: mvertes/alpine-mongo:3.2.4-1
    container_name: parsley_health_test_sv_mongodb
    restart: on-failure
    ports:
      - "27019:27017"
